apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-uploaddocs-backend
spec:
  selector:
    matchLabels:
      app: ha-uploaddocs-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: ha-uploaddocs-backend
    spec:
      containers:
        - name: ha-uploaddocs-backend
          image: ha-uploaddocs-backend:1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ha-uploaddocs-backend-np-service
spec:
  selector:
    app: ha-uploaddocs-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

